# Generated by Django 5.1 on 2024-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
